export const CREATE_DOC_REQUEST = "CREATE_DOC_REQUEST";
export const CREATE_DOC_SUCCESS = "CREATE_DOC_SUCCESS";
export const CREATE_DOC_FAILURE = "CREATE_DOC_FAILURE";
export const GET_DOC_REQUEST = "GET_DOC_REQUEST";
export const GET_DOC_SUCCESS = "GET_DOC_SUCCESS";
export const GET_DOC_FAILURE = "GET_DOC_FAILURE";
