export const MACHINE_SUGGESTIONS = "MACHINE_SUGGESTIONS";
export const PART_NO_SUGGESTIONS = "PART_NO_SUGGESTIONS";
export const DESCRIPTION_SUGGESTIONS = "DESCRIPTION_SUGGESTIONS";
export const CATEGORY_SUGGESTIONS = "CATEGORY_SUGGESTIONS";

export const CLEAR_PART_SUGGESTIONS = "CLEAR_PART_SUGGESTIONS";
